# Generated by Django 4.2.28 on 2026-03-26 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_product_food_product'),
        ('ordermanagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20, null=True)),
                ('order_date', models.DateField(null=True)),
                ('quantity', models.FloatField(null=True)),
                ('amount', models.FloatField(null=True)),
                ('gst_amount', models.FloatField(null=True)),
                ('bill_amount', models.FloatField(null=True)),
                ('Customer_reference', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ordermanagement.customer')),
                ('Product_reference', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='firstapp.product')),
            ],
        ),
    ]
