# Generated by Django 4.2.28 on 2026-02-25 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodduct',
            name='gst',
            field=models.IntegerField(default=0),
        ),
    ]
