# Generated by Django 4.2.28 on 2026-02-25 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_prodduct_gst'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='prodduct',
            new_name='product',
        ),
    ]
